# Generated by Django 6.0.6 on 2026-06-18 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='medical_info',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('librarian', 'Librarian'), ('finance_officer', 'Finance Officer'), ('transport_manager', 'Transport Manager')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(default='Finance', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Profile',
                'verbose_name_plural': 'Finance Profiles',
            },
        ),
        migrations.CreateModel(
            name='LibrarianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(default='Library', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Librarian Profile',
                'verbose_name_plural': 'Librarian Profiles',
            },
        ),
        migrations.CreateModel(
            name='TransportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(default='Transport', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport Profile',
                'verbose_name_plural': 'Transport Profiles',
            },
        ),
    ]
