# Generated by Django 6.0.6 on 2026-06-19 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_parentprofile_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('admin', 'School Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('librarian', 'Librarian'), ('finance_officer', 'Finance Officer'), ('transport_manager', 'Transport Manager')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemAdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('technical', 'Technical Only'), ('monitoring', 'Monitoring Only')], default='full', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Admin Profile',
                'verbose_name_plural': 'System Admin Profiles',
            },
        ),
    ]
