# Generated by Django 6.0.6 on 2026-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
