# Generated by Django 6.0.6 on 2026-06-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('transcripts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'course', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('student', 'academic_year', 'term')},
        ),
    ]
