# Generated by Django 6.0.6 on 2026-06-19 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        ('transcripts', '0002_initial'),
        ('users', '0002_remove_parentprofile_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=300)),
                ('school_address', models.TextField()),
                ('school_phone', models.CharField(max_length=50)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('term_info', models.TextField(help_text='Term information text')),
                ('academic_year_info', models.TextField(help_text='Academic year information')),
                ('show_grading_scale', models.BooleanField(default=True)),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_conduct', models.BooleanField(default=True)),
                ('show_remarks', models.BooleanField(default=True)),
                ('show_signature_lines', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Report Card Template',
                'verbose_name_plural': 'Report Card Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='academicrecord',
            options={'ordering': ['course__subject__name'], 'verbose_name': 'Academic Record', 'verbose_name_plural': 'Academic Records'},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-academic_year__name', '-term__name'], 'verbose_name': 'Transcript', 'verbose_name_plural': 'Transcripts'},
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='continuous_assessment',
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='continuous_assessment_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CA 1'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='continuous_assessment_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CA 2'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='continuous_assessment_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CA 3'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='teacher_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='teacher_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='total_ca',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='transcript',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transcripts', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transcript',
            name='average_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transcript',
            name='class_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='class_teacher_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='conduct_grade',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='transcript',
            name='days_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcript',
            name='days_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcript',
            name='general_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='grade_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='parent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='parent_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='principal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='transcript',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='transcript',
            name='total_students_in_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='total_students_in_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/pdfs/'),
        ),
        migrations.CreateModel(
            name='GPAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('scale', models.CharField(choices=[('4.0', '4.0 Scale'), ('5.0', '5.0 Scale'), ('12.0', '12.0 Scale')], default='4.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
            options={
                'verbose_name': 'GPA Configuration',
                'verbose_name_plural': 'GPA Configurations',
            },
        ),
        migrations.CreateModel(
            name='GradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('gpa_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_points', to='transcripts.gpaconfig')),
            ],
            options={
                'verbose_name': 'Grade Point',
                'verbose_name_plural': 'Grade Points',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('punctuality', models.CharField(default='A', max_length=5)),
                ('attendance', models.CharField(default='A', max_length=5)),
                ('neatness', models.CharField(default='A', max_length=5)),
                ('respect', models.CharField(default='A', max_length=5)),
                ('participation', models.CharField(default='A', max_length=5)),
                ('homework_completion', models.CharField(default='A', max_length=5)),
                ('teamwork', models.CharField(default='A', max_length=5)),
                ('leadership', models.CharField(default='A', max_length=5)),
                ('overall_conduct', models.CharField(default='A', max_length=5)),
                ('teacher_comments', models.TextField(blank=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_reports', to='users.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Behavioral Report',
                'verbose_name_plural': 'Behavioral Reports',
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('term1_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('term2_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('term3_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='users.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Performance',
                'verbose_name_plural': 'Subject Performances',
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
