# Generated by Django 6.0.6 on 2026-06-19 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        ('timetable', '0002_initial'),
        ('users', '0002_remove_parentprofile_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('periods_per_week', models.IntegerField(default=3)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Subject Allocation',
                'verbose_name_plural': 'Subject Allocations',
                'unique_together': {('class_assigned', 'subject', 'term')},
            },
        ),
    ]
