# Generated by Django 6.0.6 on 2026-06-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0003_subjectallocation'),
        ('users', '0003_alter_user_role_systemadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='period_name',
            field=models.CharField(blank=True, help_text='e.g., Period 1, Morning Break', max_length=50),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
    ]
