# Generated by Django 6.0.6 on 2026-06-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransportallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_allocations', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttransportallocation',
            unique_together={('student', 'academic_year')},
        ),
    ]
